/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scope */
        get: operations["scope_api_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{abbr}/opponents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opponents */
        get: operations["opponents_api_teams__abbr__opponents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{abbr}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_teams__abbr__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{abbr}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Players
         * @description `series`: last10 | all | an opponent abbreviation. It selects the series
         *     behind the tiles, both trends and the recent-series list.
         */
        get: operations["players_api_teams__abbr__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/h2h": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head To Head */
        get: operations["head_to_head_api_h2h_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/h2h/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** H2H Brief */
        post: operations["h2h_brief_api_h2h_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scrims */
        get: operations["scrims_api_scrims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrims/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scrim Options */
        get: operations["scrim_options_api_scrims_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/elo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elo */
        get: operations["elo_api_elo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training */
        get: operations["training_api_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BanHighlight */
        BanHighlight: {
            /** Mode */
            mode: string;
            /** Map Name */
            map_name: string;
            flag: components["schemas"]["Flag"];
        };
        /** Brief */
        Brief: {
            /** Text */
            text: string;
        };
        /**
         * Elo
         * @description `trajectory` is filled for view=trajectory, `current` for view=current.
         */
        Elo: {
            /**
             * View
             * @enum {string}
             */
            view: "trajectory" | "current";
            /** Seed */
            seed: number;
            /** Trajectory */
            trajectory: components["schemas"]["EloSeries"][];
            /** Current */
            current: components["schemas"]["EloCurrent"][];
        };
        /** EloCurrent */
        EloCurrent: {
            team: components["schemas"]["TeamInfo"];
            /** Elo */
            elo: number;
            /** Low Confidence */
            low_confidence: boolean;
        };
        /** EloPoint */
        EloPoint: {
            /** Match Date */
            match_date: string;
            /** Elo */
            elo: number;
            /** Opponent */
            opponent: string;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "L";
            /** Label */
            label: string;
        };
        /** EloSeries */
        EloSeries: {
            team: components["schemas"]["TeamInfo"];
            /** Low Confidence */
            low_confidence: boolean;
            /** Points */
            points: components["schemas"]["EloPoint"][];
        };
        /** EloSide */
        EloSide: {
            /** Elo */
            elo: number;
            /** Low Confidence */
            low_confidence: boolean;
        };
        /** Flag */
        Flag: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "up" | "down" | "low_sample";
            /** Label */
            label: string;
        };
        /**
         * Flagged
         * @description A numeric stat with its sample size and optional highlight.
         */
        Flagged: {
            /** Value */
            value: number | null;
            /** N */
            n: number;
            flag?: components["schemas"]["Flag"] | null;
        };
        /** H2H */
        H2H: {
            team: components["schemas"]["TeamInfo"];
            opp: components["schemas"]["TeamInfo"];
            elo: components["schemas"]["H2HElo"];
            h2h_series: components["schemas"]["WL"];
            /** Opp Recent Series */
            opp_recent_series: components["schemas"]["SeriesResult"][];
            /** Modes */
            modes: components["schemas"]["H2HMode"][];
        };
        /** H2HElo */
        H2HElo: {
            team: components["schemas"]["EloSide"];
            opp: components["schemas"]["EloSide"];
        };
        /** H2HMap */
        H2HMap: {
            /** Map Id */
            map_id: number;
            /** Map Name */
            map_name: string;
            /** Delta */
            delta: number | null;
            h2h: components["schemas"]["WL"];
            your_wl: components["schemas"]["WL"];
            opp_wl: components["schemas"]["WL"];
            your_rate: components["schemas"]["Flagged"];
            opp_rate: components["schemas"]["Flagged"];
            your_strength: components["schemas"]["Strength"];
            opp_strength: components["schemas"]["Strength"];
            your_pick_wl: components["schemas"]["WL"];
            your_defend_wl: components["schemas"]["WL"];
            opp_pick_wl: components["schemas"]["WL"];
            opp_defend_wl: components["schemas"]["WL"];
            opp_bans: components["schemas"]["Rate"];
            opp_bans_h2h: components["schemas"]["Rate"];
            opp_picks: components["schemas"]["Rate"];
            /** Tags */
            tags: ("pick" | "ban" | "they_ban")[];
        };
        /** H2HMode */
        H2HMode: {
            /** Mode */
            mode: string;
            /** Maps */
            maps: components["schemas"]["H2HMap"][];
            /** Not Enough Data */
            not_enough_data: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KdPoint */
        KdPoint: {
            /** Player Name */
            player_name: string;
            /** Match Date */
            match_date: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Kd */
            kd: number;
        };
        /** MapResult */
        MapResult: {
            /** Match Date */
            match_date: string;
            /** Opponent */
            opponent: string;
            /** Score */
            score: string;
            /** Pick Context */
            pick_context: string | null;
            /** Picked By */
            picked_by: string;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "L";
            /** Family */
            family: string;
            /** Label */
            label: string;
        };
        /** OpsPoint */
        OpsPoint: {
            /** Player Name */
            player_name: string;
            /** Match Date */
            match_date: string;
            /** Op Kills */
            op_kills: number;
            /** Op Pulls */
            op_pulls: number;
            /** Maps */
            maps: number;
            /** Kills Per Pull */
            kills_per_pull: number | null;
        };
        /** PlayerSeries */
        PlayerSeries: {
            /** Match Id */
            match_id: number;
            /** Match Date */
            match_date: string;
            /** Opponent */
            opponent: string;
            /** Our Maps */
            our_maps: number;
            /** Their Maps */
            their_maps: number;
            /** Maps */
            maps: components["schemas"]["SeriesMap"][];
        };
        /** PlayerTile */
        PlayerTile: {
            /** Player Name */
            player_name: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Games */
            games: number;
            kd: components["schemas"]["Flagged"];
            /** Avg Pos Eng Pct */
            avg_pos_eng_pct: number;
            /** Op Kills */
            op_kills: number | null;
            /** Op Pulls */
            op_pulls: number | null;
            op_kills_per_pull: components["schemas"]["Flagged"];
        };
        /** Players */
        Players: {
            /** Players */
            players: string[];
            /** Tiles */
            tiles: components["schemas"]["PlayerTile"][];
            /** Kd Trend */
            kd_trend: components["schemas"]["KdPoint"][];
            /** Ops Trend */
            ops_trend: components["schemas"]["OpsPoint"][];
            /** Recent Series */
            recent_series: components["schemas"]["PlayerSeries"][];
        };
        /** Profile */
        Profile: {
            team: components["schemas"]["TeamInfo"];
            /** Elo */
            elo: number;
            /** Low Confidence */
            low_confidence: boolean;
            record: components["schemas"]["Record"];
            /** Overall Map Win Rate */
            overall_map_win_rate: number | null;
            /** Maps */
            maps: components["schemas"]["ProfileMap"][];
            /** Ban Summary */
            ban_summary: components["schemas"]["BanHighlight"][];
        };
        /** ProfileMap */
        ProfileMap: {
            /** Map Id */
            map_id: number | null;
            /** Map Name */
            map_name: string;
            /** Mode */
            mode: string;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            win_rate: components["schemas"]["Flagged"];
            strength: components["schemas"]["Strength"];
            /** Pick Wins */
            pick_wins: number;
            /** Pick Losses */
            pick_losses: number;
            /** Defend Wins */
            defend_wins: number;
            /** Defend Losses */
            defend_losses: number;
            banned: components["schemas"]["Rate"];
            picked: components["schemas"]["Rate"];
            opp_banned: components["schemas"]["Rate"];
            /** History */
            history: components["schemas"]["MapResult"][];
        };
        /**
         * Rate
         * @description count of total series (ban/pick data is partial; total = series with data).
         */
        Rate: {
            /** Count */
            count: number;
            /** Total */
            total: number;
        };
        /** Record */
        Record: {
            /** Series Wins */
            series_wins: number;
            /** Series Losses */
            series_losses: number;
            /** Map Wins */
            map_wins: number;
            /** Map Losses */
            map_losses: number;
        };
        /** ScrimKdPoint */
        ScrimKdPoint: {
            /** Player Name */
            player_name: string;
            /** Match Date */
            match_date: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Kd */
            kd: number;
            /** Assists */
            assists: number;
            /** Games */
            games: number;
        };
        /** ScrimMap */
        ScrimMap: {
            /** Map Name */
            map_name: string;
            /** Mode */
            mode: string;
            /** Played */
            played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Pct */
            win_pct: number;
            /** Avg Margin */
            avg_margin: number | null;
            flag: components["schemas"]["Flag"] | null;
            /** Recent */
            recent: components["schemas"]["ScrimResult"][];
        };
        /** ScrimModeWL */
        ScrimModeWL: {
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Total */
            total: number;
            /** Win Pct */
            win_pct: number;
            /** Mode */
            mode: string;
        };
        /** ScrimOptions */
        ScrimOptions: {
            /** Maps */
            maps: string[];
            /** Opponents */
            opponents: components["schemas"]["TeamInfo"][];
        };
        /** ScrimResult */
        ScrimResult: {
            /** Date */
            date: string;
            /** Week */
            week: number;
            /** Opponent */
            opponent: string;
            /** Our Score */
            our_score: number;
            /** Opp Score */
            opp_score: number;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "L";
        };
        /** ScrimTrendPoint */
        ScrimTrendPoint: {
            /** Match Date */
            match_date: string;
            /** Played */
            played: number;
            /** Wins */
            wins: number;
            /** Win Pct */
            win_pct: number;
        };
        /** ScrimWL */
        ScrimWL: {
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Total */
            total: number;
            /** Win Pct */
            win_pct: number;
        };
        /** Scrims */
        Scrims: {
            overall: components["schemas"]["ScrimWL"];
            /** By Mode */
            by_mode: components["schemas"]["ScrimModeWL"][];
            /** Maps */
            maps: components["schemas"]["ScrimMap"][];
            /** Trend */
            trend: components["schemas"]["ScrimTrendPoint"][];
            /** Kd Trend */
            kd_trend: components["schemas"]["ScrimKdPoint"][];
        };
        /** SeriesMap */
        SeriesMap: {
            /** Result Id */
            result_id: number;
            /** Slot */
            slot: number;
            /** Map Name */
            map_name: string;
            /** Mode */
            mode: string;
            /** Won */
            won: boolean;
            /** Our Score */
            our_score: number;
            /** Their Score */
            their_score: number;
            /** Players */
            players: components["schemas"]["SeriesPlayer"][];
        };
        /** SeriesPlayer */
        SeriesPlayer: {
            /** Player Name */
            player_name: string;
            /** Kills */
            kills: number | null;
            /** Deaths */
            deaths: number | null;
            /** Assists */
            assists: number | null;
            /** Op Kills */
            op_kills: number | null;
            /** Op Pulls */
            op_pulls: number | null;
        };
        /** SeriesResult */
        SeriesResult: {
            /** Match Date */
            match_date: string;
            /** Opponent */
            opponent: string;
            /**
             * Result
             * @enum {string}
             */
            result: "W" | "L";
            /** Score */
            score: string;
            /** Family */
            family: string;
            /** Label */
            label: string;
        };
        /** Strength */
        Strength: {
            /** Rating */
            rating: number | null;
            /** Weighted Sample */
            weighted_sample: number;
            /** Total Played */
            total_played: number;
            /** Low Confidence */
            low_confidence: boolean;
        };
        /** TeamInfo */
        TeamInfo: {
            /** Abbreviation */
            abbreviation: string;
            /** Team Name */
            team_name: string;
            /** Primary Color */
            primary_color: string | null;
            /** Secondary Color */
            secondary_color: string | null;
            /** Logo */
            logo: string | null;
        };
        /**
         * Training
         * @description `months` lists months with any submission, ascending; `players` in recap order.
         */
        Training: {
            /** Month */
            month: string;
            /** Months */
            months: string[];
            /** Players */
            players: components["schemas"]["TrainingPlayer"][];
            /** Daily */
            daily: components["schemas"]["TrainingDay"][];
        };
        /** TrainingDay */
        TrainingDay: {
            /** Date */
            date: string;
            /** Username */
            username: string;
            /** Sessions */
            sessions: number;
        };
        /** TrainingPlayer */
        TrainingPlayer: {
            /** Username */
            username: string;
            /** Sessions */
            sessions: number;
            /** Days Trained */
            days_trained: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WL */
        WL: {
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scope_api_scope_get: {
        parameters: {
            query?: {
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opponents_api_teams__abbr__opponents_get: {
        parameters: {
            query?: {
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                abbr: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_teams__abbr__profile_get: {
        parameters: {
            query?: {
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                abbr: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_api_teams__abbr__players_get: {
        parameters: {
            query?: {
                player?: string | null;
                mode?: ("SnD" | "HP" | "Control") | null;
                series?: string;
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                abbr: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Players"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_api_h2h_get: {
        parameters: {
            query: {
                team: string;
                opp: string;
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["H2H"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    h2h_brief_api_h2h_brief_post: {
        parameters: {
            query: {
                team: string;
                opp: string;
                event?: "all" | "spring" | "summer" | "regionals";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scrims_api_scrims_get: {
        parameters: {
            query?: {
                mode?: ("SnD" | "HP" | "Control") | null;
                map?: string | null;
                opponent?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scrims"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scrim_options_api_scrims_options_get: {
        parameters: {
            query?: {
                mode?: ("SnD" | "HP" | "Control") | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrimOptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elo_api_elo_get: {
        parameters: {
            query?: {
                view?: "trajectory" | "current";
                event?: "all" | "spring" | "summer" | "regionals";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Elo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    training_api_training_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
